const Leathery: DataStuffCategory = {
  stuffs: [
    'Muffalo_Leather',
    'Gazelle_Leather',
    'Iguana_Leather',
    'Rhinoceros_Leather',
    'Dromedary_Leather',
    'GrizzlyBear_Leather',
    'PolarBear_Leather',
    'Cougar_Leather',
    'Panther_Leather',
    'Lynx_Leather',
    'Cassowary_Leather',
    'Emu_Leather',
    'Ostrich_Leather',
    'Turkey_Leather',
    'Pig_Leather',
    'Cow_Leather',
    'Alpaca_Leather',
    'Elephant_Leather',
    'Megasloth_Leather',
    'Thrumbo_Leather',
    'Hare_Leather',
    'Snowhare_Leather',
    'YorkshireTerrier_Leather',
    'Husky_Leather',
    'LabradorRetriever_Leather',
    'Cat_Leather',
    'Squirrel_Leather',
    'Alphabeaver_Leather',
    'Capybara_Leather',
    'Chinchilla_Leather',
    'Boomrat_Leather',
    'Raccoon_Leather',
    'Rat_Leather',
    'Deer_Leather',
    'Ibex_Leather',
    'Elk_Leather',
    'Caribou_Leather',
    'Tortoise_Leather',
    'Cobra_Leather',
    'Monkey_Leather',
    'Boomalope_Leather',
    'Warg_Leather',
    'WolfTimber_Leather',
    'WolfArctic_Leather',
    'FoxFennec_Leather',
    'FoxRed_Leather',
    'FoxArctic_Leather',
    'Human_Leather'
  ],
  defName: 'Leathery'
}

export default Leathery;
